### ISSUE TITLE
Thoughts on making `skip_routes` a regex?

### ISSUE THREAD

**Issue by coneybeare** [jeffsiver/fastapi-route-logger#10]
Real world use case:
- we want to ignore `status` and healthcheck hits.
- we also use api versioning, so our status endpoints look like `/1.0.0/status` and `/2.0.1/status`

Current process:
- We have to explicitly add each version to the skip_routes array because skipping routes is implemented as `request.url.path.startswith(path)]`

Desired process:
- Set a regex in that list so we can say something like `r"/.*/status"` and be done with it. (this is a contrived regex for clarity, obviously the matching of semver would need to be more robust)

If this is something you would be open to, I can submit a PR and make it backwards compatible by type checking the list item, and matching against regex only when the string can compile through re library, and `starts_with` when a string. Or I can use a new attribute `skip_routes_matching` which expects only valid regexs. Thoughts?

**Comment by jeffsiver** [comment]
I like this idea - especially since it can work with strings or regex. If you want to create the PR, I will review and merge.

**Comment by jeffsiver** [comment]
Published as version 0.2.0.
